environments:
- name: test
  config:
    plugins:
      extractors:
      - name: tap-s3-csv
        config:
          start_date: '2023-10-01T00:00:00Z'
  env:
    TARGET_BIGQUERY_DATASET_ID: dev_meltano
    TARGET_BIGQUERY_TABLE_PREFIX: dev_
    LOGLEVEL: warning
